#!/bin/bash
find . -type -name \*.gif -printf "%f\n" | LC_ALL=C sort -f | rev | cut -b 5- | refind . -type f -iname "*.gif" | while read -r file; do filename=$(echo "$file" | rev | cut -d "/" -f1 | rev | cut -d "." -f1) echo "$filename" done | sort -fv
